name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    permissions:
      deployments: write
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: bash ./scripts/create-artifacts-assets.sh
      - name: Archive build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'artifacts'
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
